"""Scaffold importability tests -- generated by Crafted Dev Agent.

SCOPE: These tests verify ONLY that each package directory is importable.
They intentionally do not test attributes, classes, or functions --
those belong in subsequent PRDs that build on this scaffold.
"""
import pytest


def test_tasklib_is_importable():
    """tasklib must be importable as an empty namespace."""
    pytest.importorskip("tasklib")


def test_tasklib_models_is_importable():
    """tasklib.models must be importable as an empty namespace."""
    pytest.importorskip("tasklib.models")


def test_tasklib_storage_is_importable():
    """tasklib.storage must be importable as an empty namespace."""
    pytest.importorskip("tasklib.storage")


def test_tasklib_cli_is_importable():
    """tasklib.cli must be importable as an empty namespace."""
    pytest.importorskip("tasklib.cli")
