"""Scaffold importability tests -- generated by Crafted Dev Agent.

SCOPE: These tests verify ONLY that each package directory is importable.
They intentionally do not test attributes, classes, or functions --
those belong in subsequent PRDs that build on this scaffold.
"""
import importlib
import sys
from pathlib import Path

# Ensure src/ is on PYTHONPATH
PROJECT_ROOT = next(
    p for p in Path(__file__).resolve().parents if (p / "pyproject.toml").exists()
)
_src = str(PROJECT_ROOT / "src")
if _src not in sys.path:
    sys.path.insert(0, _src)


def test_tasklib_is_importable():
    """Package tasklib must be importable as an empty namespace."""
    import importlib
    m = importlib.import_module("tasklib")
    assert m is not None


def test_tasklib_cli_is_importable():
    """Package tasklib.cli must be importable as an empty namespace."""
    import importlib
    m = importlib.import_module("tasklib.cli")
    assert m is not None


def test_tests_tasklib_is_importable():
    """Package tests.tasklib must be importable as an empty namespace."""
    import importlib
    m = importlib.import_module("tests.tasklib")
    assert m is not None


def test_tests_tasklib_cli_is_importable():
    """Package tests.tasklib.cli must be importable as an empty namespace."""
    import importlib
    m = importlib.import_module("tests.tasklib.cli")
    assert m is not None
